GET https://us-east1-my-project-asksumit.cloudfunctions.net/demo3


GET https://us-east1-my-project-asksumit.cloudfunctions.net/demo3?name=Jim


POST https://us-east1-my-project-asksumit.cloudfunctions.net/demo3
content-type: application/json

{
    "name": "Joyce"
}